/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.game.view;

import br.com.game.controller.GameController;

/**
 *
 * @author Adrian
 */
public class GamePartidaView extends javax.swing.JFrame {

    /**
     * Creates new form GameView
     */
    public GamePartidaView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpQuadro1 = new javax.swing.JPanel();
        txtQuadro1 = new javax.swing.JLabel();
        jpQuadro2 = new javax.swing.JPanel();
        txtQuadro2 = new javax.swing.JLabel();
        jpQuadro3 = new javax.swing.JPanel();
        txtQuadro3 = new javax.swing.JLabel();
        jpQuadro4 = new javax.swing.JPanel();
        txtQuadro4 = new javax.swing.JLabel();
        jpQuadro5 = new javax.swing.JPanel();
        txtQuadro5 = new javax.swing.JLabel();
        jpQuadro6 = new javax.swing.JPanel();
        txtQuadro6 = new javax.swing.JLabel();
        jpQuadro7 = new javax.swing.JPanel();
        txtQuadro7 = new javax.swing.JLabel();
        jpQuadro8 = new javax.swing.JPanel();
        txtQuadro8 = new javax.swing.JLabel();
        jpQuadro9 = new javax.swing.JPanel();
        txtQuadro9 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JLabel();
        txtPlayer2 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtPlayerDaVez = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jpQuadro1.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro1.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro1.setText("X");
        txtQuadro1.setToolTipText("");

        javax.swing.GroupLayout jpQuadro1Layout = new javax.swing.GroupLayout(jpQuadro1);
        jpQuadro1.setLayout(jpQuadro1Layout);
        jpQuadro1Layout.setHorizontalGroup(
            jpQuadro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro1Layout.setVerticalGroup(
            jpQuadro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro2.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro2.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro2.setText("X");
        txtQuadro2.setToolTipText("");

        javax.swing.GroupLayout jpQuadro2Layout = new javax.swing.GroupLayout(jpQuadro2);
        jpQuadro2.setLayout(jpQuadro2Layout);
        jpQuadro2Layout.setHorizontalGroup(
            jpQuadro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpQuadro2Layout.createSequentialGroup()
                .addComponent(txtQuadro2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpQuadro2Layout.setVerticalGroup(
            jpQuadro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro3.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro3.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro3.setText("X");
        txtQuadro3.setToolTipText("");

        javax.swing.GroupLayout jpQuadro3Layout = new javax.swing.GroupLayout(jpQuadro3);
        jpQuadro3.setLayout(jpQuadro3Layout);
        jpQuadro3Layout.setHorizontalGroup(
            jpQuadro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro3Layout.setVerticalGroup(
            jpQuadro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro4.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro4.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro4.setText("X");
        txtQuadro4.setToolTipText("");

        javax.swing.GroupLayout jpQuadro4Layout = new javax.swing.GroupLayout(jpQuadro4);
        jpQuadro4.setLayout(jpQuadro4Layout);
        jpQuadro4Layout.setHorizontalGroup(
            jpQuadro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro4Layout.setVerticalGroup(
            jpQuadro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro5.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro5.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro5.setText("X");
        txtQuadro5.setToolTipText("");

        javax.swing.GroupLayout jpQuadro5Layout = new javax.swing.GroupLayout(jpQuadro5);
        jpQuadro5.setLayout(jpQuadro5Layout);
        jpQuadro5Layout.setHorizontalGroup(
            jpQuadro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro5Layout.setVerticalGroup(
            jpQuadro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro6.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro6.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro6.setText("X");
        txtQuadro6.setToolTipText("");

        javax.swing.GroupLayout jpQuadro6Layout = new javax.swing.GroupLayout(jpQuadro6);
        jpQuadro6.setLayout(jpQuadro6Layout);
        jpQuadro6Layout.setHorizontalGroup(
            jpQuadro6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro6, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro6Layout.setVerticalGroup(
            jpQuadro6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro7.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro7.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro7.setText("X");
        txtQuadro7.setToolTipText("");

        javax.swing.GroupLayout jpQuadro7Layout = new javax.swing.GroupLayout(jpQuadro7);
        jpQuadro7.setLayout(jpQuadro7Layout);
        jpQuadro7Layout.setHorizontalGroup(
            jpQuadro7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro7Layout.setVerticalGroup(
            jpQuadro7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro8.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro8.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro8.setText("X");
        txtQuadro8.setToolTipText("");

        javax.swing.GroupLayout jpQuadro8Layout = new javax.swing.GroupLayout(jpQuadro8);
        jpQuadro8.setLayout(jpQuadro8Layout);
        jpQuadro8Layout.setHorizontalGroup(
            jpQuadro8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro8Layout.setVerticalGroup(
            jpQuadro8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpQuadro9.setPreferredSize(new java.awt.Dimension(150, 150));

        txtQuadro9.setFont(new java.awt.Font("Segoe UI Light", 1, 100)); // NOI18N
        txtQuadro9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuadro9.setText("X");
        txtQuadro9.setToolTipText("");

        javax.swing.GroupLayout jpQuadro9Layout = new javax.swing.GroupLayout(jpQuadro9);
        jpQuadro9.setLayout(jpQuadro9Layout);
        jpQuadro9Layout.setHorizontalGroup(
            jpQuadro9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro9, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpQuadro9Layout.setVerticalGroup(
            jpQuadro9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuadro9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpQuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpQuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpQuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jpQuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpQuadro9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jpQuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpQuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jpQuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpQuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpQuadro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpQuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpQuadro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpQuadro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpQuadro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpQuadro8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpQuadro9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpQuadro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpQuadro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        txtPlayer1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtPlayer1.setText("Player 1: ");

        txtPlayer2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtPlayer2.setText("Player 2: ");

        jLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel.setText("Vez de: ");

        txtResultado.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtResultado.setText("Resultado: ");

        btnReiniciar.setBackground(new java.awt.Color(51, 153, 255));
        btnReiniciar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnReiniciar.setForeground(new java.awt.Color(0, 0, 0));
        btnReiniciar.setText("Reiniciar");

        btnMenu.setBackground(new java.awt.Color(51, 153, 255));
        btnMenu.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        txtPlayerDaVez.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPlayerDaVez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlayer1)
                    .addComponent(txtPlayer2))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel)
                    .addComponent(txtPlayerDaVez, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReiniciar)
                    .addComponent(btnMenu))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        GameController controller = new GameController();
        controller.abreMenu();
        controller.fecharTelaPartida(this);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePartidaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpQuadro1;
    private javax.swing.JPanel jpQuadro2;
    private javax.swing.JPanel jpQuadro3;
    private javax.swing.JPanel jpQuadro4;
    private javax.swing.JPanel jpQuadro5;
    private javax.swing.JPanel jpQuadro6;
    private javax.swing.JPanel jpQuadro7;
    private javax.swing.JPanel jpQuadro8;
    private javax.swing.JPanel jpQuadro9;
    private javax.swing.JLabel txtPlayer1;
    private javax.swing.JLabel txtPlayer2;
    private javax.swing.JLabel txtPlayerDaVez;
    private javax.swing.JLabel txtQuadro1;
    private javax.swing.JLabel txtQuadro2;
    private javax.swing.JLabel txtQuadro3;
    private javax.swing.JLabel txtQuadro4;
    private javax.swing.JLabel txtQuadro5;
    private javax.swing.JLabel txtQuadro6;
    private javax.swing.JLabel txtQuadro7;
    private javax.swing.JLabel txtQuadro8;
    private javax.swing.JLabel txtQuadro9;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnMenu() {
        return btnMenu;
    }

    public void setBtnMenu(javax.swing.JButton btnMenu) {
        this.btnMenu = btnMenu;
    }

    public javax.swing.JButton getBtnReiniciar() {
        return btnReiniciar;
    }

    public void setBtnReiniciar(javax.swing.JButton btnReiniciar) {
        this.btnReiniciar = btnReiniciar;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JPanel getJpQuadro1() {
        return jpQuadro1;
    }

    public void setJpQuadro1(javax.swing.JPanel jpQuadro1) {
        this.jpQuadro1 = jpQuadro1;
    }

    public javax.swing.JPanel getJpQuadro2() {
        return jpQuadro2;
    }

    public void setJpQuadro2(javax.swing.JPanel jpQuadro2) {
        this.jpQuadro2 = jpQuadro2;
    }

    public javax.swing.JPanel getJpQuadro3() {
        return jpQuadro3;
    }

    public void setJpQuadro3(javax.swing.JPanel jpQuadro3) {
        this.jpQuadro3 = jpQuadro3;
    }

    public javax.swing.JPanel getJpQuadro4() {
        return jpQuadro4;
    }

    public void setJpQuadro4(javax.swing.JPanel jpQuadro4) {
        this.jpQuadro4 = jpQuadro4;
    }

    public javax.swing.JPanel getJpQuadro5() {
        return jpQuadro5;
    }

    public void setJpQuadro5(javax.swing.JPanel jpQuadro5) {
        this.jpQuadro5 = jpQuadro5;
    }

    public javax.swing.JPanel getJpQuadro6() {
        return jpQuadro6;
    }

    public void setJpQuadro6(javax.swing.JPanel jpQuadro6) {
        this.jpQuadro6 = jpQuadro6;
    }

    public javax.swing.JPanel getJpQuadro7() {
        return jpQuadro7;
    }

    public void setJpQuadro7(javax.swing.JPanel jpQuadro7) {
        this.jpQuadro7 = jpQuadro7;
    }

    public javax.swing.JPanel getJpQuadro8() {
        return jpQuadro8;
    }

    public void setJpQuadro8(javax.swing.JPanel jpQuadro8) {
        this.jpQuadro8 = jpQuadro8;
    }

    public javax.swing.JPanel getJpQuadro9() {
        return jpQuadro9;
    }

    public void setJpQuadro9(javax.swing.JPanel jpQuadro9) {
        this.jpQuadro9 = jpQuadro9;
    }

    public javax.swing.JLabel getTxtPlayer1() {
        return txtPlayer1;
    }

    public void setTxtPlayer1(String txtPlayer1) {
        this.txtPlayer1.setText(this.txtPlayer1.getText()+txtPlayer1);
    }

    public javax.swing.JLabel getTxtPlayer2() {
        return txtPlayer2;
    }

    public void setTxtPlayer2(String txtPlayer2) {
        this.txtPlayer2.setText(this.txtPlayer2.getText()+txtPlayer2);
    }

    public String getTxtPlayerDaVez() {
        return txtPlayerDaVez.getText();
    }

    public void setTxtPlayerDaVez(String txtPlayerDaVez) {
        this.txtPlayerDaVez.setText(txtPlayerDaVez);
    }

    public javax.swing.JLabel getTxtQuadro1() {
        return txtQuadro1;
    }

    public void setTxtQuadro1(javax.swing.JLabel txtQuadro1) {
        this.txtQuadro1 = txtQuadro1;
    }

    public javax.swing.JLabel getTxtQuadro2() {
        return txtQuadro2;
    }

    public void setTxtQuadro2(javax.swing.JLabel txtQuadro2) {
        this.txtQuadro2 = txtQuadro2;
    }

    public javax.swing.JLabel getTxtQuadro3() {
        return txtQuadro3;
    }

    public void setTxtQuadro3(javax.swing.JLabel txtQuadro3) {
        this.txtQuadro3 = txtQuadro3;
    }

    public javax.swing.JLabel getTxtQuadro4() {
        return txtQuadro4;
    }

    public void setTxtQuadro4(javax.swing.JLabel txtQuadro4) {
        this.txtQuadro4 = txtQuadro4;
    }

    public javax.swing.JLabel getTxtQuadro5() {
        return txtQuadro5;
    }

    public void setTxtQuadro5(javax.swing.JLabel txtQuadro5) {
        this.txtQuadro5 = txtQuadro5;
    }

    public javax.swing.JLabel getTxtQuadro6() {
        return txtQuadro6;
    }

    public void setTxtQuadro6(javax.swing.JLabel txtQuadro6) {
        this.txtQuadro6 = txtQuadro6;
    }

    public javax.swing.JLabel getTxtQuadro7() {
        return txtQuadro7;
    }

    public void setTxtQuadro7(javax.swing.JLabel txtQuadro7) {
        this.txtQuadro7 = txtQuadro7;
    }

    public javax.swing.JLabel getTxtQuadro8() {
        return txtQuadro8;
    }

    public void setTxtQuadro8(javax.swing.JLabel txtQuadro8) {
        this.txtQuadro8 = txtQuadro8;
    }

    public javax.swing.JLabel getTxtQuadro9() {
        return txtQuadro9;
    }

    public void setTxtQuadro9(javax.swing.JLabel txtQuadro9) {
        this.txtQuadro9 = txtQuadro9;
    }

    public String getTxtResultado() {
        return txtResultado.getText();
    }

    public void setTxtResultado(String txtResultado) {
        this.txtResultado.setText(txtResultado);
    }
}
